/**
 * Created by yuan on 2018/6/15.
 */

export const GET_LIST_ASYNC = 'GET_LIST_ASYNC'
export const GET_LIST = 'GET_LIST'


export const GET_LIST_REPO_ASYNC = 'GET_LIST_REPO_ASYNC'
export const GET_LIST_REPO = 'GET_LIST_REPO'


export const GET_LIST_FOLLOWER_ASYNC = 'GET_LIST_FOLLOWER_ASYNC'
export const GET_LIST_FOLLOWER = 'GET_LIST_FOLLOWER'


export const GET_LIST_FOLLOWING_ASYNC = 'GET_LIST_FOLLOWING_ASYNC'
export const GET_LIST_FOLLOWING = 'GET_LIST_FOLLOWING'


export const GET_NAME_ASYNC = 'GET_NAME_ASYNC'
export const GET_NAME= 'GET_NAME'


export const CLEAN_STATE= 'CLEAN_STATE'

